---
title: "key_crop_yields"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{key_crop_yields}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cwdata)
library(tidyverse)
```

```{r}
key_crop_yields %>% 
  filter(year == 2017) %>% 
  group_by(crop) %>% 
  summarise(tonnes_per_hectare = sum(tonnes_per_hectare, na.rm = T)) %>% 
  ggplot(aes(x = forcats::fct_reorder(crop, tonnes_per_hectare, .desc = T), 
             y = tonnes_per_hectare)) + 
  geom_col()+
  theme_bw()+
  labs(
    y = "Tonnes per hectare",
    x = "Crop",
    title = "Glboal crop production"
  )
```
The most produced crop in the world is potatoes! Has this always been the case?

```{r}
key_crop_yields  %>% 
  group_by(year, crop) %>% 
  summarise(tonnes_per_hectare = sum(tonnes_per_hectare, na.rm = T)) %>% 
  ggplot(aes(x = year, 
             y = tonnes_per_hectare,
             colour = crop)) + 
  geom_line()+
  theme_bw()+
  labs(
    y = "Tonnes per hectare",
    x = "Crop",
    title = "Glboal crop production"
  )
```

Looks like potatoes have always widely grown, but before 1997 bananas took the top spot!
